config/routes.rb
Cosolving::Application.routes.draw do
  devise_for :users
  resources :problems do
    collection do
      get :multi
      post :create_multi
    end
    member do
      put :start
      put :abandon
      put :finish
      put :re_solve
    end
  end
  root 'problems#index'

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :start_time
  validates_presence_of :end_time
  has_many :solvings

  def user_status user_id
    query = Solving.where(user_id: user_id, problem_id: id)
    if query.empty?
      "untouched"
    else
      query.first.status
    end
  end
end

app/models/progress.rb
class Progress < ActiveRecord::Base
end

app/models/solving.rb
class Solving < ActiveRecord::Base
  belongs_to :problem
  belongs_to :user
  validates_uniqueness_of :user_id, scope: :problem_id
  validates_presence_of :user, :problem
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :solvings

  def nickname
    email[/[^@]+/]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user_id
    current_user ? current_user.id : nil
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]

  def index
    @problems = Problem.all

    @solvings = Solving.where(problem_id: @problems).
                        group_by(&:problem_id)
  end

  def show
  end

  def new
    @problem = Problem.new
  end

  def edit
  end

  def create
    @problem = Problem.new(problem_params)
    if @problem.save
      redirect_to @problem, notice: 'Problem was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @problem.update(problem_params)
      redirect_to @problem, notice: 'Problem was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @problem.destroy
    redirect_to problems_url
  end

  def multi
  end

  def create_multi
    params[:quantity].to_i.times do |number|
      @problem = Problem.new(name: "Zadanie #{(number+1)}", start_time: params[:start_time], end_time: params[:end_time])
      @problem.save
    end
    redirect_to problems_path, notice: "Yey! You have created new problems"
  end

  def start
    @solving = Solving.new(user_id: current_user_id, status: :solving, problem_id: params[:id])
    if @solving.save
      redirect_to problems_path
    else
      redirect_to problems_path, alert: "Log in to start solving"
    end
  end

  def re_solve
    @solving = Solving.where(user_id: current_user_id, problem_id: params[:id]).first
    update_solving_status :solving
  end

  def finish
    @solving = Solving.where(user_id: current_user_id, problem_id: params[:id]).first
    update_solving_status :finished
  end

  def abandon
    @solving = Solving.where(user_id: current_user_id, problem_id: params[:id]).first
    update_solving_status :abandoned
  end

  private

  def update_solving_status status
    if @solving
      @solving.update(status: status)
      redirect_to problems_path
    else
      redirect_to problems_path, alert: "You havent started solving yet"
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_problem
    @problem = Problem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def problem_params
    params.permit(:name, :start_time, :end_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    !current_user.nil? and current_user.is_admin
  end

  def current_user_id
    unless current_user.nil?
      return current_user.id
    end
    nil
  end

  def humanize secs
    [[60, :seconds], [60, :minutes], [24, :hours], [1000, :days]].map{ |count, name|
      if secs > 0
        secs, n = secs.divmod(count)
        "#{n.to_i} #{name}"
      end
    }.compact.reverse.join(' ')
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Cosolving"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Co-Solving", root_url, class: "brand"

          .container.nav-collapse
            %ul.nav
              %li= link_to "Problems", problems_path
              - if is_admin?
                %li= link_to "Multi", multi_problems_path
                %li= link_to "New", new_problem_path
            %ul.nav.pull-right
              - if user_signed_in?
                %li= link_to current_user.email, edit_user_registration_path
                %li= link_to 'Logout', destroy_user_session_path, :method => :delete
              - else
                %li= link_to 'Login', new_user_session_path
                %li= link_to 'Register', new_user_registration_path

    .container

      .row
        .span9
          = bootstrap_flash
          - if is_admin?
            admin panel
          = yield
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Historia
              %li= link_to "Tydzień 1", problems_path

      %footer
        %p &copy; Michał Żurkowski

app/views/problems/_badge.html.haml
- if solving.status == "finished"
  .badge.label-success #{solving.user.nickname}
- elsif solving.status == "abandoned"
  .badge.label #{solving.user.nickname}
- elsif solving.status == "solving"
  .badge.label-info #{solving.user.nickname} (since #{humanize Time.now - solving.updated_at})

app/views/problems/_form.html.haml
= form_for @problem, :html => { :class => 'form-horizontal' } do |f|
  = render 'shared/form_errors', object: @problem

  .control-group
    = label :name, :name, :class => 'control-label'
    .controls
      = text_field_tag :name, "", :class => 'text_field'
  .control-group
    = label :start_time, :start_time, :class => 'control-label'
    .controls
      = datetime_local_field_tag :start_time, :class => 'datetime_field'
  .control-group
    = label :end_time, :end_time, :class => 'control-label'
    .controls
      = datetime_local_field_tag :end_time, :class => 'datetime_field'
  .form-actions
    = submit_tag nil, :class => 'btn btn-primary', data: { confirm: "Are you sure?" }
    = link_to t('.cancel', :default => t("helpers.links.cancel")), problems_path, :class => 'btn'

app/views/problems/edit.html.haml
- model_class = Problem
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/problems/index.html.haml
:javascript
  var dupa=1;

- model_class = Problem
.page-header
  %h1 Tydzień 1
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:solving)
      %th Actions
      - if is_admin?
        %th admin
  %tbody
    - @problems.each do |problem|
      %tr
        %td= problem.name
        %td
          - unless @solvings[problem.id].nil?
            - @solvings[problem.id].each do |solving|
              = render 'badge', solving: solving

        - if problem.user_status(current_user_id) == "untouched"
          %td= link_to "Start", start_problem_path(problem), method: :put, class: 'btn btn-info btn-mini'
        - elsif problem.user_status(current_user_id) == "solving"
          %td
            = link_to "Finish", finish_problem_path(problem), method: :put, class: 'btn btn-success btn-mini'
            = link_to "Abandon", abandon_problem_path(problem), method: :put, class: 'btn btn btn-mini'
        - elsif problem.user_status(current_user_id) == "finished"
          %td= link_to "Resolve?", re_solve_problem_path(problem), method: :put, class: 'btn btn-info btn-mini'
        - elsif problem.user_status(current_user_id) == "abandoned"
          %td= link_to "Try again", re_solve_problem_path(problem), method: :put, class: 'btn btn-info btn-mini'

        - if is_admin?
          %td
            = link_to t('.destroy', :default => t("helpers.links.destroy")), problem_path(problem), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_problem_path(problem), :class => 'btn btn-mini'
%br
%br
Legend:
.badge.label-info Solving
.badge.label-success Finished
.badge.label Abandoned
%br
%br
%br

- if is_admin?
  = link_to t('.new', :default => t("helpers.links.new")), new_problem_path, :class => 'btn btn-mini'
  = link_to t('.multi', :default => t("helpers.links.multi")), multi_problems_path, :class => 'btn btn-mini'

app/views/problems/multi.html.haml
- model_class = Problem
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.pluralize.titleize

= form_tag create_multi_problems_path, method: :post, class: 'form-horizontal' do |f|
  .control-group
    = label :name, :quantity, :class => 'control-label'
    .controls
      = text_field_tag :quantity, "", class: :text_field
  .control-group
    = label :start_time, :start_time, :class => 'control-label'
    .controls
      = datetime_local_field_tag :start_time, class: :datetime_field
  .control-group
    = label :end_time, :end_time, :class => 'control-label'
    .controls
      = datetime_local_field_tag :end_time, class: :datetime_field
  .form-actions
    = submit_tag :Create, :class => 'btn btn-primary', data: { confirm: "Are you sure?" }
    = link_to t('.cancel', :default => t("helpers.links.cancel")), problems_path, :class => 'btn'

app/views/problems/new.html.haml
- model_class = Problem
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/problems/show.html.haml
- model_class = Problem
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @problem.name
%p
  %strong= model_class.human_attribute_name(:start_time) + ':'
  %br
  = @problem.start_time
%p
  %strong= model_class.human_attribute_name(:end_time) + ':'
  %br
  = @problem.end_time

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), problems_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_problem_path(@problem), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), problem_path(@problem), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/shared/_form_errors.html.haml
- if object.errors.any?
  %ul
    - object.errors.full_messages.each do |msg|
      %li= msg